const weapons = [
    {
        "name": "stone axe",
        "type": "Axes",
        "blunt": "0",
        "pierce": "0",
        "slash": "30",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "0"
    },
    {
        "name": "flint axe",
        "type": "Axes",
        "blunt": "0",
        "pierce": "0",
        "slash": "35",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "0"
    },
    {
        "name": "bronze axe",
        "type": "Axes",
        "blunt": "0",
        "pierce": "0",
        "slash": "55",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "0"
    },
    {
        "name": "iron axe",
        "type": "Axes",
        "blunt": "0",
        "pierce": "0",
        "slash": "75",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "0"
    },
    {
        "name": "blackmetal axe",
        "type": "Axes",
        "blunt": "0",
        "pierce": "0",
        "slash": "115",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "0"
    },
    {
        "name": "battleaxe",
        "type": "Axes",
        "blunt": "0",
        "pierce": "0",
        "slash": "88",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "0"
    },
    {
        "name": "crystal battleaxe",
        "type": "Axes",
        "blunt": "0",
        "pierce": "0",
        "slash": "108",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "30"
    },
    {
        "name": "crude bow",
        "type": "Bows",
        "blunt": "0",
        "pierce": "31",
        "slash": "0",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "0"
    },
    {
        "name": "finewood bow",
        "type": "Bows",
        "blunt": "0",
        "pierce": "41",
        "slash": "0",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "0"
    },
    {
        "name": "huntsman bow",
        "type": "Bows",
        "blunt": "0",
        "pierce": "51",
        "slash": "0",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "0"
    },
    {
        "name": "draugr fang",
        "type": "Bows",
        "blunt": "0",
        "pierce": "56",
        "slash": "0",
        "frost": "0",
        "fire": "0",
        "poison": "20",
        "spirit": "0"
    },
    {
        "name": "club",
        "type": "Clubs",
        "blunt": "30",
        "pierce": "0",
        "slash": "0",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "0"
    },
    {
        "name": "torch",
        "type": "Clubs",
        "blunt": "4",
        "pierce": "0",
        "slash": "0",
        "frost": "0",
        "fire": "15",
        "poison": "0",
        "spirit": "0"
    },
    {
        "name": "bronze mace",
        "type": "Clubs",
        "blunt": "53",
        "pierce": "0",
        "slash": "0",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "0"
    },
    {
        "name": "iron mace",
        "type": "Clubs",
        "blunt": "73",
        "pierce": "0",
        "slash": "0",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "0"
    },
    {
        "name": "frostner",
        "type": "Clubs",
        "blunt": "35",
        "pierce": "0",
        "slash": "0",
        "frost": "58",
        "fire": "0",
        "poison": "0",
        "spirit": "20"
    },
    {
        "name": "porcupine",
        "type": "Clubs",
        "blunt": "50",
        "pierce": "63",
        "slash": "0",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "0"
    },
    {
        "name": "stagbreaker",
        "type": "Clubs",
        "blunt": "38",
        "pierce": "5",
        "slash": "0",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "0"
    },
    {
        "name": "iron sledge",
        "type": "Clubs",
        "blunt": "73",
        "pierce": "0",
        "slash": "0",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "0"
    },
    {
        "name": "bare fists",
        "type": "Fists",
        "blunt": "5",
        "pierce": "0",
        "slash": "0",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "0"
    },
    {
        "name": "flesh rippers",
        "type": "Fists",
        "blunt": "0",
        "pierce": "0",
        "slash": "76",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "0"
    },
    {
        "name": "flint knife",
        "type": "Knives",
        "blunt": "0",
        "pierce": "8",
        "slash": "8",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "0"
    },
    {
        "name": "copper knife",
        "type": "Knives",
        "blunt": "0",
        "pierce": "15",
        "slash": "15",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "0"
    },
    {
        "name": "abyssal razor",
        "type": "Knives",
        "blunt": "0",
        "pierce": "23",
        "slash": "23",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "0"
    },
    {
        "name": "silver knife",
        "type": "Knives",
        "blunt": "0",
        "pierce": "28",
        "slash": "28",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "12"
    },
    {
        "name": "blackmetal knife",
        "type": "Knives",
        "blunt": "0",
        "pierce": "37",
        "slash": "37",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "0"
    },
    {
        "name": "antler pickaxe",
        "type": "Pickaxes",
        "blunt": "0",
        "pierce": "18",
        "slash": "0",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "0"
    },
    {
        "name": "bronze pickaxe",
        "type": "Pickaxes",
        "blunt": "0",
        "pierce": "40",
        "slash": "0",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "0"
    },
    {
        "name": "iron pickaxe",
        "type": "Pickaxes",
        "blunt": "0",
        "pierce": "48",
        "slash": "0",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "0"
    },
    {
        "name": "bronze atgeir",
        "type": "Polearms",
        "blunt": "0",
        "pierce": "63",
        "slash": "0",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "0"
    },
    {
        "name": "iron atgeir",
        "type": "Polearms",
        "blunt": "0",
        "pierce": "83",
        "slash": "0",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "0"
    },
    {
        "name": "blackmetal atgeir",
        "type": "Polearms",
        "blunt": "0",
        "pierce": "123",
        "slash": "0",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "0"
    },
    {
        "name": "flint spear",
        "type": "Spears",
        "blunt": "0",
        "pierce": "38",
        "slash": "0",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "0"
    },
    {
        "name": "bronze spear",
        "type": "Spears",
        "blunt": "0",
        "pierce": "53",
        "slash": "0",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "0"
    },
    {
        "name": "abyssal harpoon",
        "type": "Spears",
        "blunt": "0",
        "pierce": "10",
        "slash": "0",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "0"
    },
    {
        "name": "ancient bark spear",
        "type": "Spears",
        "blunt": "0",
        "pierce": "73",
        "slash": "0",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "0"
    },
    {
        "name": "fang spear",
        "type": "Spears",
        "blunt": "0",
        "pierce": "93",
        "slash": "0",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "0"
    },
    {
        "name": "bronze sword",
        "type": "Swords",
        "blunt": "0",
        "pierce": "0",
        "slash": "53",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "0"
    },
    {
        "name": "iron sword",
        "type": "Swords",
        "blunt": "0",
        "pierce": "0",
        "slash": "73",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "0"
    },
    {
        "name": "silver sword",
        "type": "Swords",
        "blunt": "0",
        "pierce": "0",
        "slash": "93",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "45"
    },
    {
        "name": "blackmetal sword",
        "type": "Swords",
        "blunt": "0",
        "pierce": "0",
        "slash": "113",
        "frost": "0",
        "fire": "0",
        "poison": "0",
        "spirit": "0"
    }
];
export default weapons;